name: Preview Docs

on: pull_request

jobs:
  preview-docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate preview URL
        id: generate-docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          OUTPUT=$(fern generate --docs --preview 2>&1) || true
          echo "$OUTPUT"
          URL=$(echo "$OUTPUT" | grep -oP 'Published docs to \K.*(?= \()')
          echo "url=$URL" >> "$GITHUB_OUTPUT"

      - name: Add Status Check
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.generate-docs.outputs.url }}';
            const pr = context.payload.pull_request;
            const response = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: pr.head.sha,
              state: "success",
              target_url: url,
              description: "Docs Preview URL",
            });
